# Default values for moj-fastapi-skeleton.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

environment: development

ingress:
  enabled: true
  tls:
    - hosts:
        - "moj-fastapi-skeleton.cloud-platform.service.justice.gov.uk"
  hosts:
    - host: "moj-fastapi-skeleton.cloud-platform.service.justice.gov.uk"
      paths:
        - path: /
          pathType: ImplementationSpecific