# Default values for laa-civil-case-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas:
  app: 2

environment: staging

ingress:
  enabled: false
  hosts:
    - host: "laa-civil-case-api-staging.cloud-platform.service.justice.gov.uk"
      paths:
        - path: /
          pathType: ImplementationSpecific