# Default values for laa-civil-case-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

environment: development

ingress:
  enabled: true
  tls:
    - hosts:
        - "laa-civil-case-api-dev.cloud-platform.service.justice.gov.uk"
  hosts:
    - host: "laa-civil-case-api-dev.cloud-platform.service.justice.gov.uk"
      paths:
        - path: /
          pathType: ImplementationSpecific